### PR TITLE
Sync 4.4.7 branch with imgsystem linux

### PR DESCRIPTION
**Pull request by ghost**
I did not include patch "ZONE_DMA: RPU 64MB Limitation: Avoiding Bounce Buffers" because enabling GENERIC_ISA_DMA cause a crash of the wifi and cascoda drivers.

### CODE REVIEW

**Comment by ghost** [comment]
test with ca8210 profile

**Review by abhijit-mahajani-imgtec — COMMENTED** [review]
Should we take this one?Since it was done for production tests.

**Comment by ghost** [comment]
@abhijit-mahajani-imgtec You mean the commit concerning cc2520 ?

**Comment by abhijit-mahajani-imgtec** [comment]
Approved

**Pull request merged**
